[package]
name = "gqnrs"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "~2.27.0", features = ["yaml"]}
tch = "0.0.8"
yaml-rust = "0.3.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
image = "0.18.0"
glob = "0.3.0"
telamon-utils = { git = "https://github.com/ulysseB/telamon.git" }
protobuf = { version = "2", features = ["with-bytes"] }
byteorder = "1"
crc = "1.8.1"
ndarray = { version = "0.12.1", features = ["blas"] }
blas-src = { version = "0.2.0", default-features = false, features = ["openblas"] }
openblas-src = { version = "0.6.0", default-features = false, features = ["cblas", "system"] }