cargo-features = ["profile-overrides"]

[package]
name = "gqnrs"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "^2.27", features = ["yaml"]}
# tch = "^0.0"
tch = { git = "https://github.com/LaurentMazare/tch-rs.git", branch = "master" }
yaml-rust = "^0.3"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
image = "^0.18"
glob = "^0.3"
protobuf = { version = "^2", features = ["with-bytes"] }
byteorder = "^1"
crc = "^1.8"
rayon = "^1.0"
log = "^0.4"
tfrecord-rs = { git = "ssh://git@wtf.csie.org:/srv/git/tfrecord-rs.git", branch = "dev" }
maplit = "^1.0"
pretty_env_logger = "^0.3"
ndarray = "^0.12"
par-map = "^0.1"
itertools = "^0.8"
crossbeam = "^0.7"
ctrlc = "^3.1"
lazy_static = "^1.3"
# cv = { git = "https://github.com/nebgnahz/cv-rs.git" }
# opencv = "^0.14"
hdf5 = "^0.5"
regex = "^1"
signal-hook = "^0.1"

[dev-dependencies]
rv = "^0.5"

# [profile.dev.overrides."*"]
# opt-level = 2
