[package]
name = "gqnrs"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "^2.27", features = ["yaml"]}
# tch = "^0.0"
tch = { git = "https://github.com/LaurentMazare/tch-rs.git", branch = "master" }
yaml-rust = "^0"
serde = { version = "^1", features = ["derive"] }
serde_json = "^1"
image = "^0"
glob = "^0"
protobuf = { version = "^2", features = ["with-bytes"] }
byteorder = "^1"
crc = "^1"
rayon = "^1"
log = "^0"
tfrecord-rs = { git = "https://github.com/jerry73204/tfrecord-rs.git", branch = "master" }
maplit = "^1"
pretty_env_logger = "^0"
ndarray = "^0"
par-map = "^0"
itertools = "^0"
crossbeam = "^0"
ctrlc = "^3"
lazy_static = "^1"
hdf5 = "^0"
regex = "^1"
failure = "^0"

[dev-dependencies]
rv = "^0"
