[package]
name = "gqnrs"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

[dependencies]
clap = {version = "~2.27.0", features = ["yaml"]}
tch = "0.0.8"
yaml-rust = "0.3.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
image = "*"
telamon_utils = "*"
