// This file is generated by rust-protobuf 2.5.0. Do not edit
// @generated

// https://github.com/Manishearth/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy)]

#![cfg_attr(rustfmt, rustfmt_skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]

use protobuf::Message as Message_imported_for_functions;
use protobuf::ProtobufEnum as ProtobufEnum_imported_for_functions;

#[derive(PartialEq,Clone,Default)]
pub struct VarLenFeatureProto {
    // message fields
    pub dtype: super::types::DataType,
    pub values_output_tensor_name: ::std::string::String,
    pub indices_output_tensor_name: ::std::string::String,
    pub shapes_output_tensor_name: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a VarLenFeatureProto {
    fn default() -> &'a VarLenFeatureProto {
        <VarLenFeatureProto as ::protobuf::Message>::default_instance()
    }
}

impl VarLenFeatureProto {
    pub fn new() -> VarLenFeatureProto {
        ::std::default::Default::default()
    }

    // .tensorflow.DataType dtype = 1;


    pub fn get_dtype(&self) -> super::types::DataType {
        self.dtype
    }
    pub fn clear_dtype(&mut self) {
        self.dtype = super::types::DataType::DT_INVALID;
    }

    // Param is passed by value, moved
    pub fn set_dtype(&mut self, v: super::types::DataType) {
        self.dtype = v;
    }

    // string values_output_tensor_name = 2;


    pub fn get_values_output_tensor_name(&self) -> &str {
        &self.values_output_tensor_name
    }
    pub fn clear_values_output_tensor_name(&mut self) {
        self.values_output_tensor_name.clear();
    }

    // Param is passed by value, moved
    pub fn set_values_output_tensor_name(&mut self, v: ::std::string::String) {
        self.values_output_tensor_name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_values_output_tensor_name(&mut self) -> &mut ::std::string::String {
        &mut self.values_output_tensor_name
    }

    // Take field
    pub fn take_values_output_tensor_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.values_output_tensor_name, ::std::string::String::new())
    }

    // string indices_output_tensor_name = 3;


    pub fn get_indices_output_tensor_name(&self) -> &str {
        &self.indices_output_tensor_name
    }
    pub fn clear_indices_output_tensor_name(&mut self) {
        self.indices_output_tensor_name.clear();
    }

    // Param is passed by value, moved
    pub fn set_indices_output_tensor_name(&mut self, v: ::std::string::String) {
        self.indices_output_tensor_name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_indices_output_tensor_name(&mut self) -> &mut ::std::string::String {
        &mut self.indices_output_tensor_name
    }

    // Take field
    pub fn take_indices_output_tensor_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.indices_output_tensor_name, ::std::string::String::new())
    }

    // string shapes_output_tensor_name = 4;


    pub fn get_shapes_output_tensor_name(&self) -> &str {
        &self.shapes_output_tensor_name
    }
    pub fn clear_shapes_output_tensor_name(&mut self) {
        self.shapes_output_tensor_name.clear();
    }

    // Param is passed by value, moved
    pub fn set_shapes_output_tensor_name(&mut self, v: ::std::string::String) {
        self.shapes_output_tensor_name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_shapes_output_tensor_name(&mut self) -> &mut ::std::string::String {
        &mut self.shapes_output_tensor_name
    }

    // Take field
    pub fn take_shapes_output_tensor_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.shapes_output_tensor_name, ::std::string::String::new())
    }
}

impl ::protobuf::Message for VarLenFeatureProto {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.dtype, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.values_output_tensor_name)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.indices_output_tensor_name)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.shapes_output_tensor_name)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.dtype != super::types::DataType::DT_INVALID {
            my_size += ::protobuf::rt::enum_size(1, self.dtype);
        }
        if !self.values_output_tensor_name.is_empty() {
            my_size += ::protobuf::rt::string_size(2, &self.values_output_tensor_name);
        }
        if !self.indices_output_tensor_name.is_empty() {
            my_size += ::protobuf::rt::string_size(3, &self.indices_output_tensor_name);
        }
        if !self.shapes_output_tensor_name.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.shapes_output_tensor_name);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.dtype != super::types::DataType::DT_INVALID {
            os.write_enum(1, self.dtype.value())?;
        }
        if !self.values_output_tensor_name.is_empty() {
            os.write_string(2, &self.values_output_tensor_name)?;
        }
        if !self.indices_output_tensor_name.is_empty() {
            os.write_string(3, &self.indices_output_tensor_name)?;
        }
        if !self.shapes_output_tensor_name.is_empty() {
            os.write_string(4, &self.shapes_output_tensor_name)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> VarLenFeatureProto {
        VarLenFeatureProto::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<super::types::DataType>>(
                    "dtype",
                    |m: &VarLenFeatureProto| { &m.dtype },
                    |m: &mut VarLenFeatureProto| { &mut m.dtype },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "values_output_tensor_name",
                    |m: &VarLenFeatureProto| { &m.values_output_tensor_name },
                    |m: &mut VarLenFeatureProto| { &mut m.values_output_tensor_name },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "indices_output_tensor_name",
                    |m: &VarLenFeatureProto| { &m.indices_output_tensor_name },
                    |m: &mut VarLenFeatureProto| { &mut m.indices_output_tensor_name },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "shapes_output_tensor_name",
                    |m: &VarLenFeatureProto| { &m.shapes_output_tensor_name },
                    |m: &mut VarLenFeatureProto| { &mut m.shapes_output_tensor_name },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<VarLenFeatureProto>(
                    "VarLenFeatureProto",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static VarLenFeatureProto {
        static mut instance: ::protobuf::lazy::Lazy<VarLenFeatureProto> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const VarLenFeatureProto,
        };
        unsafe {
            instance.get(VarLenFeatureProto::new)
        }
    }
}

impl ::protobuf::Clear for VarLenFeatureProto {
    fn clear(&mut self) {
        self.dtype = super::types::DataType::DT_INVALID;
        self.values_output_tensor_name.clear();
        self.indices_output_tensor_name.clear();
        self.shapes_output_tensor_name.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for VarLenFeatureProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for VarLenFeatureProto {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct FixedLenFeatureProto {
    // message fields
    pub dtype: super::types::DataType,
    pub shape: ::protobuf::SingularPtrField<super::tensor_shape::TensorShapeProto>,
    pub default_value: ::protobuf::SingularPtrField<super::tensor::TensorProto>,
    pub values_output_tensor_name: ::std::string::String,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a FixedLenFeatureProto {
    fn default() -> &'a FixedLenFeatureProto {
        <FixedLenFeatureProto as ::protobuf::Message>::default_instance()
    }
}

impl FixedLenFeatureProto {
    pub fn new() -> FixedLenFeatureProto {
        ::std::default::Default::default()
    }

    // .tensorflow.DataType dtype = 1;


    pub fn get_dtype(&self) -> super::types::DataType {
        self.dtype
    }
    pub fn clear_dtype(&mut self) {
        self.dtype = super::types::DataType::DT_INVALID;
    }

    // Param is passed by value, moved
    pub fn set_dtype(&mut self, v: super::types::DataType) {
        self.dtype = v;
    }

    // .tensorflow.TensorShapeProto shape = 2;


    pub fn get_shape(&self) -> &super::tensor_shape::TensorShapeProto {
        self.shape.as_ref().unwrap_or_else(|| super::tensor_shape::TensorShapeProto::default_instance())
    }
    pub fn clear_shape(&mut self) {
        self.shape.clear();
    }

    pub fn has_shape(&self) -> bool {
        self.shape.is_some()
    }

    // Param is passed by value, moved
    pub fn set_shape(&mut self, v: super::tensor_shape::TensorShapeProto) {
        self.shape = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_shape(&mut self) -> &mut super::tensor_shape::TensorShapeProto {
        if self.shape.is_none() {
            self.shape.set_default();
        }
        self.shape.as_mut().unwrap()
    }

    // Take field
    pub fn take_shape(&mut self) -> super::tensor_shape::TensorShapeProto {
        self.shape.take().unwrap_or_else(|| super::tensor_shape::TensorShapeProto::new())
    }

    // .tensorflow.TensorProto default_value = 3;


    pub fn get_default_value(&self) -> &super::tensor::TensorProto {
        self.default_value.as_ref().unwrap_or_else(|| super::tensor::TensorProto::default_instance())
    }
    pub fn clear_default_value(&mut self) {
        self.default_value.clear();
    }

    pub fn has_default_value(&self) -> bool {
        self.default_value.is_some()
    }

    // Param is passed by value, moved
    pub fn set_default_value(&mut self, v: super::tensor::TensorProto) {
        self.default_value = ::protobuf::SingularPtrField::some(v);
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_default_value(&mut self) -> &mut super::tensor::TensorProto {
        if self.default_value.is_none() {
            self.default_value.set_default();
        }
        self.default_value.as_mut().unwrap()
    }

    // Take field
    pub fn take_default_value(&mut self) -> super::tensor::TensorProto {
        self.default_value.take().unwrap_or_else(|| super::tensor::TensorProto::new())
    }

    // string values_output_tensor_name = 4;


    pub fn get_values_output_tensor_name(&self) -> &str {
        &self.values_output_tensor_name
    }
    pub fn clear_values_output_tensor_name(&mut self) {
        self.values_output_tensor_name.clear();
    }

    // Param is passed by value, moved
    pub fn set_values_output_tensor_name(&mut self, v: ::std::string::String) {
        self.values_output_tensor_name = v;
    }

    // Mutable pointer to the field.
    // If field is not initialized, it is initialized with default value first.
    pub fn mut_values_output_tensor_name(&mut self) -> &mut ::std::string::String {
        &mut self.values_output_tensor_name
    }

    // Take field
    pub fn take_values_output_tensor_name(&mut self) -> ::std::string::String {
        ::std::mem::replace(&mut self.values_output_tensor_name, ::std::string::String::new())
    }
}

impl ::protobuf::Message for FixedLenFeatureProto {
    fn is_initialized(&self) -> bool {
        for v in &self.shape {
            if !v.is_initialized() {
                return false;
            }
        };
        for v in &self.default_value {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_proto3_enum_with_unknown_fields_into(wire_type, is, &mut self.dtype, 1, &mut self.unknown_fields)?
                },
                2 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.shape)?;
                },
                3 => {
                    ::protobuf::rt::read_singular_message_into(wire_type, is, &mut self.default_value)?;
                },
                4 => {
                    ::protobuf::rt::read_singular_proto3_string_into(wire_type, is, &mut self.values_output_tensor_name)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if self.dtype != super::types::DataType::DT_INVALID {
            my_size += ::protobuf::rt::enum_size(1, self.dtype);
        }
        if let Some(ref v) = self.shape.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if let Some(ref v) = self.default_value.as_ref() {
            let len = v.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        }
        if !self.values_output_tensor_name.is_empty() {
            my_size += ::protobuf::rt::string_size(4, &self.values_output_tensor_name);
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if self.dtype != super::types::DataType::DT_INVALID {
            os.write_enum(1, self.dtype.value())?;
        }
        if let Some(ref v) = self.shape.as_ref() {
            os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if let Some(ref v) = self.default_value.as_ref() {
            os.write_tag(3, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        }
        if !self.values_output_tensor_name.is_empty() {
            os.write_string(4, &self.values_output_tensor_name)?;
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> FixedLenFeatureProto {
        FixedLenFeatureProto::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeEnum<super::types::DataType>>(
                    "dtype",
                    |m: &FixedLenFeatureProto| { &m.dtype },
                    |m: &mut FixedLenFeatureProto| { &mut m.dtype },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::tensor_shape::TensorShapeProto>>(
                    "shape",
                    |m: &FixedLenFeatureProto| { &m.shape },
                    |m: &mut FixedLenFeatureProto| { &mut m.shape },
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_ptr_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::tensor::TensorProto>>(
                    "default_value",
                    |m: &FixedLenFeatureProto| { &m.default_value },
                    |m: &mut FixedLenFeatureProto| { &mut m.default_value },
                ));
                fields.push(::protobuf::reflect::accessor::make_simple_field_accessor::<_, ::protobuf::types::ProtobufTypeString>(
                    "values_output_tensor_name",
                    |m: &FixedLenFeatureProto| { &m.values_output_tensor_name },
                    |m: &mut FixedLenFeatureProto| { &mut m.values_output_tensor_name },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<FixedLenFeatureProto>(
                    "FixedLenFeatureProto",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static FixedLenFeatureProto {
        static mut instance: ::protobuf::lazy::Lazy<FixedLenFeatureProto> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const FixedLenFeatureProto,
        };
        unsafe {
            instance.get(FixedLenFeatureProto::new)
        }
    }
}

impl ::protobuf::Clear for FixedLenFeatureProto {
    fn clear(&mut self) {
        self.dtype = super::types::DataType::DT_INVALID;
        self.shape.clear();
        self.default_value.clear();
        self.values_output_tensor_name.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for FixedLenFeatureProto {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FixedLenFeatureProto {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct FeatureConfiguration {
    // message oneof groups
    pub config: ::std::option::Option<FeatureConfiguration_oneof_config>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a FeatureConfiguration {
    fn default() -> &'a FeatureConfiguration {
        <FeatureConfiguration as ::protobuf::Message>::default_instance()
    }
}

#[derive(Clone,PartialEq,Debug)]
pub enum FeatureConfiguration_oneof_config {
    fixed_len_feature(FixedLenFeatureProto),
    var_len_feature(VarLenFeatureProto),
}

impl FeatureConfiguration {
    pub fn new() -> FeatureConfiguration {
        ::std::default::Default::default()
    }

    // .tensorflow.FixedLenFeatureProto fixed_len_feature = 1;


    pub fn get_fixed_len_feature(&self) -> &FixedLenFeatureProto {
        match self.config {
            ::std::option::Option::Some(FeatureConfiguration_oneof_config::fixed_len_feature(ref v)) => v,
            _ => FixedLenFeatureProto::default_instance(),
        }
    }
    pub fn clear_fixed_len_feature(&mut self) {
        self.config = ::std::option::Option::None;
    }

    pub fn has_fixed_len_feature(&self) -> bool {
        match self.config {
            ::std::option::Option::Some(FeatureConfiguration_oneof_config::fixed_len_feature(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_fixed_len_feature(&mut self, v: FixedLenFeatureProto) {
        self.config = ::std::option::Option::Some(FeatureConfiguration_oneof_config::fixed_len_feature(v))
    }

    // Mutable pointer to the field.
    pub fn mut_fixed_len_feature(&mut self) -> &mut FixedLenFeatureProto {
        if let ::std::option::Option::Some(FeatureConfiguration_oneof_config::fixed_len_feature(_)) = self.config {
        } else {
            self.config = ::std::option::Option::Some(FeatureConfiguration_oneof_config::fixed_len_feature(FixedLenFeatureProto::new()));
        }
        match self.config {
            ::std::option::Option::Some(FeatureConfiguration_oneof_config::fixed_len_feature(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_fixed_len_feature(&mut self) -> FixedLenFeatureProto {
        if self.has_fixed_len_feature() {
            match self.config.take() {
                ::std::option::Option::Some(FeatureConfiguration_oneof_config::fixed_len_feature(v)) => v,
                _ => panic!(),
            }
        } else {
            FixedLenFeatureProto::new()
        }
    }

    // .tensorflow.VarLenFeatureProto var_len_feature = 2;


    pub fn get_var_len_feature(&self) -> &VarLenFeatureProto {
        match self.config {
            ::std::option::Option::Some(FeatureConfiguration_oneof_config::var_len_feature(ref v)) => v,
            _ => VarLenFeatureProto::default_instance(),
        }
    }
    pub fn clear_var_len_feature(&mut self) {
        self.config = ::std::option::Option::None;
    }

    pub fn has_var_len_feature(&self) -> bool {
        match self.config {
            ::std::option::Option::Some(FeatureConfiguration_oneof_config::var_len_feature(..)) => true,
            _ => false,
        }
    }

    // Param is passed by value, moved
    pub fn set_var_len_feature(&mut self, v: VarLenFeatureProto) {
        self.config = ::std::option::Option::Some(FeatureConfiguration_oneof_config::var_len_feature(v))
    }

    // Mutable pointer to the field.
    pub fn mut_var_len_feature(&mut self) -> &mut VarLenFeatureProto {
        if let ::std::option::Option::Some(FeatureConfiguration_oneof_config::var_len_feature(_)) = self.config {
        } else {
            self.config = ::std::option::Option::Some(FeatureConfiguration_oneof_config::var_len_feature(VarLenFeatureProto::new()));
        }
        match self.config {
            ::std::option::Option::Some(FeatureConfiguration_oneof_config::var_len_feature(ref mut v)) => v,
            _ => panic!(),
        }
    }

    // Take field
    pub fn take_var_len_feature(&mut self) -> VarLenFeatureProto {
        if self.has_var_len_feature() {
            match self.config.take() {
                ::std::option::Option::Some(FeatureConfiguration_oneof_config::var_len_feature(v)) => v,
                _ => panic!(),
            }
        } else {
            VarLenFeatureProto::new()
        }
    }
}

impl ::protobuf::Message for FeatureConfiguration {
    fn is_initialized(&self) -> bool {
        if let Some(FeatureConfiguration_oneof_config::fixed_len_feature(ref v)) = self.config {
            if !v.is_initialized() {
                return false;
            }
        }
        if let Some(FeatureConfiguration_oneof_config::var_len_feature(ref v)) = self.config {
            if !v.is_initialized() {
                return false;
            }
        }
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.config = ::std::option::Option::Some(FeatureConfiguration_oneof_config::fixed_len_feature(is.read_message()?));
                },
                2 => {
                    if wire_type != ::protobuf::wire_format::WireTypeLengthDelimited {
                        return ::std::result::Result::Err(::protobuf::rt::unexpected_wire_type(wire_type));
                    }
                    self.config = ::std::option::Option::Some(FeatureConfiguration_oneof_config::var_len_feature(is.read_message()?));
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        if let ::std::option::Option::Some(ref v) = self.config {
            match v {
                &FeatureConfiguration_oneof_config::fixed_len_feature(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
                &FeatureConfiguration_oneof_config::var_len_feature(ref v) => {
                    let len = v.compute_size();
                    my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
                },
            };
        }
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        if let ::std::option::Option::Some(ref v) = self.config {
            match v {
                &FeatureConfiguration_oneof_config::fixed_len_feature(ref v) => {
                    os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
                &FeatureConfiguration_oneof_config::var_len_feature(ref v) => {
                    os.write_tag(2, ::protobuf::wire_format::WireTypeLengthDelimited)?;
                    os.write_raw_varint32(v.get_cached_size())?;
                    v.write_to_with_cached_sizes(os)?;
                },
            };
        }
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> FeatureConfiguration {
        FeatureConfiguration::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, FixedLenFeatureProto>(
                    "fixed_len_feature",
                    FeatureConfiguration::has_fixed_len_feature,
                    FeatureConfiguration::get_fixed_len_feature,
                ));
                fields.push(::protobuf::reflect::accessor::make_singular_message_accessor::<_, VarLenFeatureProto>(
                    "var_len_feature",
                    FeatureConfiguration::has_var_len_feature,
                    FeatureConfiguration::get_var_len_feature,
                ));
                ::protobuf::reflect::MessageDescriptor::new::<FeatureConfiguration>(
                    "FeatureConfiguration",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static FeatureConfiguration {
        static mut instance: ::protobuf::lazy::Lazy<FeatureConfiguration> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const FeatureConfiguration,
        };
        unsafe {
            instance.get(FeatureConfiguration::new)
        }
    }
}

impl ::protobuf::Clear for FeatureConfiguration {
    fn clear(&mut self) {
        self.config = ::std::option::Option::None;
        self.config = ::std::option::Option::None;
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for FeatureConfiguration {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for FeatureConfiguration {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
pub struct ExampleParserConfiguration {
    // message fields
    pub feature_map: ::std::collections::HashMap<::std::string::String, FeatureConfiguration>,
    // special fields
    pub unknown_fields: ::protobuf::UnknownFields,
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ExampleParserConfiguration {
    fn default() -> &'a ExampleParserConfiguration {
        <ExampleParserConfiguration as ::protobuf::Message>::default_instance()
    }
}

impl ExampleParserConfiguration {
    pub fn new() -> ExampleParserConfiguration {
        ::std::default::Default::default()
    }

    // repeated .tensorflow.ExampleParserConfiguration.FeatureMapEntry feature_map = 1;


    pub fn get_feature_map(&self) -> &::std::collections::HashMap<::std::string::String, FeatureConfiguration> {
        &self.feature_map
    }
    pub fn clear_feature_map(&mut self) {
        self.feature_map.clear();
    }

    // Param is passed by value, moved
    pub fn set_feature_map(&mut self, v: ::std::collections::HashMap<::std::string::String, FeatureConfiguration>) {
        self.feature_map = v;
    }

    // Mutable pointer to the field.
    pub fn mut_feature_map(&mut self) -> &mut ::std::collections::HashMap<::std::string::String, FeatureConfiguration> {
        &mut self.feature_map
    }

    // Take field
    pub fn take_feature_map(&mut self) -> ::std::collections::HashMap<::std::string::String, FeatureConfiguration> {
        ::std::mem::replace(&mut self.feature_map, ::std::collections::HashMap::new())
    }
}

impl ::protobuf::Message for ExampleParserConfiguration {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_map_into::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeMessage<FeatureConfiguration>>(wire_type, is, &mut self.feature_map)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::compute_map_size::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeMessage<FeatureConfiguration>>(1, &self.feature_map);
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream) -> ::protobuf::ProtobufResult<()> {
        ::protobuf::rt::write_map_with_cached_sizes::<::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeMessage<FeatureConfiguration>>(1, &self.feature_map, os)?;
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &::std::any::Any {
        self as &::std::any::Any
    }
    fn as_any_mut(&mut self) -> &mut ::std::any::Any {
        self as &mut ::std::any::Any
    }
    fn into_any(self: Box<Self>) -> ::std::boxed::Box<::std::any::Any> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ExampleParserConfiguration {
        ExampleParserConfiguration::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static mut descriptor: ::protobuf::lazy::Lazy<::protobuf::reflect::MessageDescriptor> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ::protobuf::reflect::MessageDescriptor,
        };
        unsafe {
            descriptor.get(|| {
                let mut fields = ::std::vec::Vec::new();
                fields.push(::protobuf::reflect::accessor::make_map_accessor::<_, ::protobuf::types::ProtobufTypeString, ::protobuf::types::ProtobufTypeMessage<FeatureConfiguration>>(
                    "feature_map",
                    |m: &ExampleParserConfiguration| { &m.feature_map },
                    |m: &mut ExampleParserConfiguration| { &mut m.feature_map },
                ));
                ::protobuf::reflect::MessageDescriptor::new::<ExampleParserConfiguration>(
                    "ExampleParserConfiguration",
                    fields,
                    file_descriptor_proto()
                )
            })
        }
    }

    fn default_instance() -> &'static ExampleParserConfiguration {
        static mut instance: ::protobuf::lazy::Lazy<ExampleParserConfiguration> = ::protobuf::lazy::Lazy {
            lock: ::protobuf::lazy::ONCE_INIT,
            ptr: 0 as *const ExampleParserConfiguration,
        };
        unsafe {
            instance.get(ExampleParserConfiguration::new)
        }
    }
}

impl ::protobuf::Clear for ExampleParserConfiguration {
    fn clear(&mut self) {
        self.feature_map.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ExampleParserConfiguration {
    fn fmt(&self, f: &mut ::std::fmt::Formatter) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ExampleParserConfiguration {
    fn as_ref(&self) -> ::protobuf::reflect::ProtobufValueRef {
        ::protobuf::reflect::ProtobufValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n:tensorflow/core/example/example_parser_configuration.proto\x12\ntenso\
    rflow\x1a,tensorflow/core/framework/tensor_shape.proto\x1a&tensorflow/co\
    re/framework/tensor.proto\x1a%tensorflow/core/framework/types.proto\"\
    \xf3\x01\n\x12VarLenFeatureProto\x12*\n\x05dtype\x18\x01\x20\x01(\x0e2\
    \x14.tensorflow.DataTypeR\x05dtype\x129\n\x19values_output_tensor_name\
    \x18\x02\x20\x01(\tR\x16valuesOutputTensorName\x12;\n\x1aindices_output_\
    tensor_name\x18\x03\x20\x01(\tR\x17indicesOutputTensorName\x129\n\x19sha\
    pes_output_tensor_name\x18\x04\x20\x01(\tR\x16shapesOutputTensorName\"\
    \xef\x01\n\x14FixedLenFeatureProto\x12*\n\x05dtype\x18\x01\x20\x01(\x0e2\
    \x14.tensorflow.DataTypeR\x05dtype\x122\n\x05shape\x18\x02\x20\x01(\x0b2\
    \x1c.tensorflow.TensorShapeProtoR\x05shape\x12<\n\rdefault_value\x18\x03\
    \x20\x01(\x0b2\x17.tensorflow.TensorProtoR\x0cdefaultValue\x129\n\x19val\
    ues_output_tensor_name\x18\x04\x20\x01(\tR\x16valuesOutputTensorName\"\
    \xba\x01\n\x14FeatureConfiguration\x12N\n\x11fixed_len_feature\x18\x01\
    \x20\x01(\x0b2\x20.tensorflow.FixedLenFeatureProtoH\0R\x0ffixedLenFeatur\
    e\x12H\n\x0fvar_len_feature\x18\x02\x20\x01(\x0b2\x1e.tensorflow.VarLenF\
    eatureProtoH\0R\rvarLenFeatureB\x08\n\x06config\"\xd6\x01\n\x1aExamplePa\
    rserConfiguration\x12W\n\x0bfeature_map\x18\x01\x20\x03(\x0b26.tensorflo\
    w.ExampleParserConfiguration.FeatureMapEntryR\nfeatureMap\x1a_\n\x0fFeat\
    ureMapEntry\x12\x10\n\x03key\x18\x01\x20\x01(\tR\x03key\x126\n\x05value\
    \x18\x02\x20\x01(\x0b2\x20.tensorflow.FeatureConfigurationR\x05value:\
    \x028\x01B|\n\x16org.tensorflow.exampleB\x20ExampleParserConfigurationPr\
    otosP\x01Z;github.com/tensorflow/tensorflow/tensorflow/go/core/example\
    \xf8\x01\x01J\xd4\x08\n\x06\x12\x04\x02\0&\x02\nV\n\x01\x0c\x12\x03\x02\
    \0\x122L\x20Protocol\x20messages\x20for\x20describing\x20the\x20configur\
    ation\x20of\x20the\x20ExampleParserOp.\n\n\x08\n\x01\x08\x12\x03\x04\0\
    \x1f\n\t\n\x02\x08\x1f\x12\x03\x04\0\x1f\n\x08\n\x01\x08\x12\x03\x05\0A\
    \n\t\n\x02\x08\x08\x12\x03\x05\0A\n\x08\n\x01\x08\x12\x03\x06\0\"\n\t\n\
    \x02\x08\n\x12\x03\x06\0\"\n\x08\n\x01\x08\x12\x03\x07\0/\n\t\n\x02\x08\
    \x01\x12\x03\x07\0/\n\x08\n\x01\x08\x12\x03\x08\0R\n\t\n\x02\x08\x0b\x12\
    \x03\x08\0R\n\x08\n\x01\x02\x12\x03\t\0\x13\n\t\n\x02\x03\0\x12\x03\x0b\
    \06\n\t\n\x02\x03\x01\x12\x03\x0c\00\n\t\n\x02\x03\x02\x12\x03\r\0/\n\n\
    \n\x02\x04\0\x12\x04\x0f\0\x14\x01\n\n\n\x03\x04\0\x01\x12\x03\x0f\x08\
    \x1a\n\x0b\n\x04\x04\0\x02\0\x12\x03\x10\x02\x20\n\r\n\x05\x04\0\x02\0\
    \x04\x12\x04\x10\x02\x0f\x1c\n\x0c\n\x05\x04\0\x02\0\x06\x12\x03\x10\x02\
    \x15\n\x0c\n\x05\x04\0\x02\0\x01\x12\x03\x10\x16\x1b\n\x0c\n\x05\x04\0\
    \x02\0\x03\x12\x03\x10\x1e\x1f\n\x0b\n\x04\x04\0\x02\x01\x12\x03\x11\x02\
    '\n\r\n\x05\x04\0\x02\x01\x04\x12\x04\x11\x02\x10\x20\n\x0c\n\x05\x04\0\
    \x02\x01\x05\x12\x03\x11\x02\x08\n\x0c\n\x05\x04\0\x02\x01\x01\x12\x03\
    \x11\t\"\n\x0c\n\x05\x04\0\x02\x01\x03\x12\x03\x11%&\n\x0b\n\x04\x04\0\
    \x02\x02\x12\x03\x12\x02(\n\r\n\x05\x04\0\x02\x02\x04\x12\x04\x12\x02\
    \x11'\n\x0c\n\x05\x04\0\x02\x02\x05\x12\x03\x12\x02\x08\n\x0c\n\x05\x04\
    \0\x02\x02\x01\x12\x03\x12\t#\n\x0c\n\x05\x04\0\x02\x02\x03\x12\x03\x12&\
    '\n\x0b\n\x04\x04\0\x02\x03\x12\x03\x13\x02'\n\r\n\x05\x04\0\x02\x03\x04\
    \x12\x04\x13\x02\x12(\n\x0c\n\x05\x04\0\x02\x03\x05\x12\x03\x13\x02\x08\
    \n\x0c\n\x05\x04\0\x02\x03\x01\x12\x03\x13\t\"\n\x0c\n\x05\x04\0\x02\x03\
    \x03\x12\x03\x13%&\n\n\n\x02\x04\x01\x12\x04\x16\0\x1b\x01\n\n\n\x03\x04\
    \x01\x01\x12\x03\x16\x08\x1c\n\x0b\n\x04\x04\x01\x02\0\x12\x03\x17\x02\
    \x20\n\r\n\x05\x04\x01\x02\0\x04\x12\x04\x17\x02\x16\x1e\n\x0c\n\x05\x04\
    \x01\x02\0\x06\x12\x03\x17\x02\x15\n\x0c\n\x05\x04\x01\x02\0\x01\x12\x03\
    \x17\x16\x1b\n\x0c\n\x05\x04\x01\x02\0\x03\x12\x03\x17\x1e\x1f\n\x0b\n\
    \x04\x04\x01\x02\x01\x12\x03\x18\x02(\n\r\n\x05\x04\x01\x02\x01\x04\x12\
    \x04\x18\x02\x17\x20\n\x0c\n\x05\x04\x01\x02\x01\x06\x12\x03\x18\x02\x1d\
    \n\x0c\n\x05\x04\x01\x02\x01\x01\x12\x03\x18\x1e#\n\x0c\n\x05\x04\x01\
    \x02\x01\x03\x12\x03\x18&'\n\x0b\n\x04\x04\x01\x02\x02\x12\x03\x19\x02+\
    \n\r\n\x05\x04\x01\x02\x02\x04\x12\x04\x19\x02\x18(\n\x0c\n\x05\x04\x01\
    \x02\x02\x06\x12\x03\x19\x02\x18\n\x0c\n\x05\x04\x01\x02\x02\x01\x12\x03\
    \x19\x19&\n\x0c\n\x05\x04\x01\x02\x02\x03\x12\x03\x19)*\n\x0b\n\x04\x04\
    \x01\x02\x03\x12\x03\x1a\x02'\n\r\n\x05\x04\x01\x02\x03\x04\x12\x04\x1a\
    \x02\x19+\n\x0c\n\x05\x04\x01\x02\x03\x05\x12\x03\x1a\x02\x08\n\x0c\n\
    \x05\x04\x01\x02\x03\x01\x12\x03\x1a\t\"\n\x0c\n\x05\x04\x01\x02\x03\x03\
    \x12\x03\x1a%&\n\n\n\x02\x04\x02\x12\x04\x1d\0\"\x01\n\n\n\x03\x04\x02\
    \x01\x12\x03\x1d\x08\x1c\n\x0c\n\x04\x04\x02\x08\0\x12\x04\x1e\x02!\x03\
    \n\x0c\n\x05\x04\x02\x08\0\x01\x12\x03\x1e\x08\x0e\n\x0b\n\x04\x04\x02\
    \x02\0\x12\x03\x1f\x04/\n\x0c\n\x05\x04\x02\x02\0\x06\x12\x03\x1f\x04\
    \x18\n\x0c\n\x05\x04\x02\x02\0\x01\x12\x03\x1f\x19*\n\x0c\n\x05\x04\x02\
    \x02\0\x03\x12\x03\x1f-.\n\x0b\n\x04\x04\x02\x02\x01\x12\x03\x20\x04+\n\
    \x0c\n\x05\x04\x02\x02\x01\x06\x12\x03\x20\x04\x16\n\x0c\n\x05\x04\x02\
    \x02\x01\x01\x12\x03\x20\x17&\n\x0c\n\x05\x04\x02\x02\x01\x03\x12\x03\
    \x20)*\n\n\n\x02\x04\x03\x12\x04$\0&\x01\n\n\n\x03\x04\x03\x01\x12\x03$\
    \x08\"\n\x0b\n\x04\x04\x03\x02\0\x12\x03%\x024\n\r\n\x05\x04\x03\x02\0\
    \x04\x12\x04%\x02$$\n\x0c\n\x05\x04\x03\x02\0\x06\x12\x03%\x02#\n\x0c\n\
    \x05\x04\x03\x02\0\x01\x12\x03%$/\n\x0c\n\x05\x04\x03\x02\0\x03\x12\x03%\
    23b\x06proto3\
";

static mut file_descriptor_proto_lazy: ::protobuf::lazy::Lazy<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::lazy::Lazy {
    lock: ::protobuf::lazy::ONCE_INIT,
    ptr: 0 as *const ::protobuf::descriptor::FileDescriptorProto,
};

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    unsafe {
        file_descriptor_proto_lazy.get(|| {
            parse_descriptor_proto()
        })
    }
}
